import mongoose from 'mongoose';
import { INTERVIEW_STATUS } from '../../constants/interviewStatus.js';
import { INTERVIEW_TYPES } from '../../constants/interviewTypes.js';

const interviewSessionSchema = new mongoose.Schema({
  candidate: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  interviewType: { type: String, enum: Object.values(INTERVIEW_TYPES), required: true },
  selectedSubjects: [{ type: String }],
  selectedTopics: [{ type: String }],
  syllabusIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Syllabus' }],
  difficulty: { type: String, enum: ['easy', 'medium', 'hard'], required: true },
  totalQuestions: { type: Number, default: 5 },
  duration: { type: Number, default: 15 },
  status: { type: String, enum: Object.values(INTERVIEW_STATUS), default: INTERVIEW_STATUS.ACTIVE },
  startedAt: Date,
  endedAt: Date,
  currentQuestionIndex: { type: Number, default: 0 },
  followUpCount: { type: Number, default: 0 },
  askedQuestions: [{ type: String }],
  askedTopics: [{ type: String }],
  currentTopic: String,
  crossQuestionCount: { type: Number, default: 0 },
  maxCrossQuestions: { type: Number, default: 2 },
  resumeContext: { type: mongoose.Schema.Types.Mixed },
  interviewMemory: { type: mongoose.Schema.Types.Mixed },
  skillGraph: { type: mongoose.Schema.Types.Mixed },
  conversationGraph: { type: mongoose.Schema.Types.Mixed },
  topicDepth: { type: mongoose.Schema.Types.Mixed },
  interviewState: { type: mongoose.Schema.Types.Mixed },
  questionHistory: [{
    questionText: { type: String, required: true },
    questionType: { type: String, enum: ['main', 'followup', 'clarification', 'closing'], default: 'main' },
    topic: String,
    subject: String,
    expectedConcepts: [{ type: String }],
    answerTranscript: String,
    extractedContext: { type: mongoose.Schema.Types.Mixed },
    askedAt: { type: Date, default: Date.now },
    answeredAt: Date,
  }],
  evaluationNotes: [{
    questionText: String,
    topic: String,
    score: Number,
    strengths: [{ type: String }],
    gaps: [{ type: String }],
    brief: String,
    createdAt: { type: Date, default: Date.now },
  }],
  finalEvaluation: {
    overallPerformance: String,
    strongestAreas: [{ type: String }],
    areasNeedingImprovement: [{ type: String }],
    communicationQuality: String,
    recommendedPracticePlan: [{ type: String }],
    summary: String,
    generatedAt: Date,
  },
  conversationHistory: [{
    sender: String,
    type: String,
    text: String,
    sequenceNumber: Number,
    createdAt: { type: Date, default: Date.now },
  }],
}, { timestamps: true });

export const InterviewSession = mongoose.models.InterviewSession || mongoose.model('InterviewSession', interviewSessionSchema);
