export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  FEATURES: '/features',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  CANDIDATE_DASHBOARD: '/candidate/dashboard',
  PROFILE_SETUP: '/candidate/profile',
  INTERVIEW_CONFIGURATION: '/candidate/interview/configure',
  INTERVIEW_SESSION: '/candidate/interview/session',
  RESUME_UPLOAD: '/candidate/resume',
  EVALUATION_RESULT: '/candidate/results/evaluation',
  FEEDBACK_REPORT: '/candidate/results/feedback',
  PRACTICE_PLAN: '/candidate/practice-plan',
  NOTIFICATIONS: '/candidate/notifications',
  ADMIN_DASHBOARD: '/admin/dashboard',
  QUESTION_BANK: '/admin/question-bank',
  ADD_QUESTION: '/admin/question-bank/add',
  MANAGE_RUBRICS: '/admin/rubrics',
  USER_REPORTS: '/admin/reports',
  AUDIT_LOGS: '/admin/audit-logs',
  NOT_FOUND: '*',
};
